### ISSUE TITLE
Missing some function declarations

### ISSUE THREAD

**Issue by MichalLytek** [types/npm-pug#1]
There no declarations of some pug functions like `compileClient` or `compileClientWithDependenciesTracked`. The old jade typings are compatible?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cc3d223a946f661eff871787edeb0fcb8f0db156/jade/jade.d.ts
Could you extend this typings to match with pug API?

**Comment by felixfbecker** [comment]
@19majkel94 Feel free to do a PR :)

**Comment by MichalLytek** [comment]
@felixfbecker, I would love to, but I got error:
`remote: Permission to types/npm-pug.git denied to 19majkel94.`
And I don't know if it's related to https (only ssh works) or this repo has disabled branch ability.

**Comment by felixfbecker** [comment]
Did you try to push to the repo?

**Comment by MichalLytek** [comment]
Yes, I cloned this repo, made some changes, made a commit and tried to push to master but got error `remote: Permission to types/npm-pug.git denied to 19majkel94.
fatal: unable to access 'https://github.com/types/npm-pug.git/': The requested URL returned error: 403`.
So a did `git checkout -q -b bug-1` and then `git push -u origin bug-1` but i got error of permission denied.

**Comment by unional** [comment]
@19majkel94, what you need to do is to fork the repo, make change on your own fork, and then create a pull request.

**Comment by felixfbecker** [comment]
you cannot push to the repo directly. You need to press the _Fork_ button on GitHub to fork the repo to your account. Then you push the branch to your fork. Then you can open a pull request. That's how it works on all GitHub OS projects 😉

**Comment by MichalLytek** [comment]
Sorry for that, I only use git at work, never did anything with opensource on GitHub. But done in #2.

**Comment by MichalLytek** [comment]
@blakeembrey, please feel free to unify params and intefraces names - I changed some of them but not sure whether they are meaningful :pensive:
