### ISSUE TITLE
can you please make a new release

### ISSUE THREAD

**Issue by dotob** [types/npm-pug#7]
the release 2.0.2 does not have the anyobject as options. this is necessary when you want to give pug some object for rendering.

**Comment by felixfbecker** [comment]
If the commit hash is outdated in the registry, you can just do a PR to update it :)

**Comment by dotob** [comment]
happy to make a pr. any hints what/where?

...

**Comment by felixfbecker** [comment]
https://github.com/typings/registry/blob/master/npm/pug.json

**Comment by felixfbecker** [comment]
Actually, looks like it is the newest commit? Are you using `typings`? If you are using NPM or tsd, it will pull the typings from DT, which are probably outdated. They will get replaced once redirects are implemented.

**Comment by dotob** [comment]
i am using npm. but i still dont understand what todo. i read the types guideline but theres nothing of help. 

...

**Comment by felixfbecker** [comment]
Run

```
npm install -g typings
typings install --save pug
```

the typings from the registry are not yet available through NPM.

**Comment by blakeembrey** [comment]
@dotob If you're using `@types/pug`, you'll need to complain on https://github.com/DefinitelyTyped/DefinitelyTyped as it's published from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pug/pug.d.ts. Or comment on https://github.com/Microsoft/types-publisher/issues/4 to show your support. As a temporary workaround as this repo has no `typings` dependencies, you could do `npm install types/npm-pug` to install from GitHub directly.
